# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4255adabdac2483cf18ca6c79700885aeb3422c19a8501e745e87ad6e1d4955eff7646b2a44e552fc8fc036c10655a0aeb469386060e038b9d146d7aafdf7afb

test:
  secret_key_base: 9eba46cff5c6e87457b51458b4a0b6d4855c98a3df39cebbc40c7b195f34a768443eafcbe4f89aa071e5aeb53f5dd85c772a5c684c4b25971265192bd7c46a60

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
